version: "3.9"

services:
  win11-vm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_ARG: "latest"
    container_name: win11-vm
    ports:
      - "3389:3389"
      - "8006:8006"
    volumes:
      - win11-data:/storage
    environment:
      VERSION: "11"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "64G"
      STORAGE_PATH: "/storage"
      KVM: "N"
      USER_PORTS: "3389 8006"
    restart: unless-stopped

volumes:
  win11-data:
    driver: local
