[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[service.win11-vm]
startCommand = "/usr/bin/tini -s /run/entry.sh"

[service.win11-vm.environment]
VERSION = "11"
RAM_SIZE = "4G"
CPU_CORES = "2"
DISK_SIZE = "64G"
STORAGE_PATH = "/storage"
KVM = "N"
USER_PORTS = "3389 8006"

[service.win11-vm.storage.win11-data]
mountPath = "/storage"
