[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[service.win11-vm]
startCommand = "/usr/bin/tini -s /run/entry.sh"

[service.win11-vm.environment]
VERSION = "11"
RAM_SIZE = "32G"
CPU_CORES = "12"
DISK_SIZE = "500G"
STORAGE_PATH = "/storage"

[service.win11-vm.storage.win11-data]
mountPath = "/storage"
